USE NFL;
GO

IF OBJECT_ID('dbo.play_by_play', 'U') IS NOT NULL
DROP TABLE dbo.play_by_play;
GO

CREATE TABLE dbo.play_by_play
(
	GAME_DATE DATE
	,GAME_ID INT
	,PLAY_ID INT
	,DRIVE INT
	,QTR INT
	,DOWN INT
	,GAME_TIME VARCHAR(10) 
	,TIME_UNDER INT
	,TIME_SECS INT
	,PLAY_TIME_DIFF INT
	,SIDE_OF_FIELD VARCHAR(5)
	,YARD_LINE INT
	,YARD_LINE_100 INT
	,YARDS_TO_GO INT
	,YARDS_NET INT
	,GOAL_TO_GO INT
	,FIRST_DOWN BIT
	,POS_TEAM VARCHAR(5)
	,DEF_TEAM VARCHAR(5)
	,PLAY_ATTEMPTED INT 
	,YARDS_GAINED INT --Negatives
	,SP BIT
	,TOUCHDOWN BIT
	,EX_POINT_RESULT VARCHAR(25)
	,TWO_POINT_CONVERSION VARCHAR(25)
	,DEF_TWO_POINT VARCHAR(25)
	,SAFETY BIT
	,ONSIDE_KICK BIT
	,PUNT_RESULT VARCHAR(25)
	,PLAY_TYPE VARCHAR(25)
	,PASSER VARCHAR(50)
	,PASSER_ID VARCHAR(20)
	,PASS_ATTEMPT BIT
	,PASS_OUTCOME VARCHAR(25)
	,PASS_LENGTH VARCHAR(25)
	,AIR_YARDS INT
	,YARDS_AFTER_CATCH INT
	,QB_HIT BIT
	,PASS_LOCATION VARCHAR(25)
	,INTERCEPTION_THROWN BIT
	,INTERCEPTOR VARCHAR(50)
	,RUSHER VARCHAR(50)
	,RUSHER_ID VARCHAR(20)
	,RUSH_ATTEMPT BIT
	,RUN_LOCATION VARCHAR(10)
	,RUN_GAP VARCHAR(10)
	,RECEIVER VARCHAR(50)
	,RECEIVER_ID VARCHAR(20)
	,RECEPTION BIT
	,RETURN_RESULT VARCHAR(20)
	,RETURNER VARCHAR(50)
	,BLOCKING_PLAYER VARCHAR(50)
	,TACKLER_1 VARCHAR(50)
	,TACKLER_2 VARCHAR(50)
	,FIELD_GOAL_RESULT VARCHAR(50)
	,FIELD_GOAL_DISTANCE INT
	,FUMBLE BIT
	,REC_FUMB_TEAM VARCHAR(10)
	,REC_FUMB_PLAYER VARCHAR(50)
	,SACK BIT
	,CHALLENGE_REPLAY BIT
	,CHALLENGE_REPLAY_RESULT VARCHAR(100)
	,ACCEPTED_PENALTY BIT
	,PENALIZED_TEAM VARCHAR(10)
	,PENALIZED_PLAYER VARCHAR(50)
	,PENALTY_YARDS INT
	,POS_TEAM_SCORE INT
	,DEF_TEAM_SCORE INT
	,SCORE_DIFF INT
	,ABS_SCORE_DIFF INT
	,HOME_TEAM VARCHAR(10)
	,AWAY_TEAM VARCHAR(10)
	,TIMEOUT_INDICATOR BIT
	,TIMEOUT_TEAM VARCHAR(10)
	,POSTEAM_TIMEOUTS_PRE INT
	,HOME_TIMEOUTS_REMAINING_PRE INT
	,AWAY_TIMEOUTS_REMAINING_PRE INT
	,HOME_TIMEOUTS_REMAINING_POST INT
	,AWAY_TIMEOUTS_REMAINING_POST INT
	,SEASON VARCHAR(20)
	,INSERT_DATE DATETIME DEFAULT GETDATE()
);
GO